import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import sveltePlugin from 'esbuild-svelte';
import { sveltePreprocess } from 'svelte-preprocess';

const banner = `/*
Generated by esbuild. Source: https://github.com/jonyardley/obsidian-task-master
*/
`;

const prod = process.argv[2] === 'production';

const config = {
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  // Obsidian supplies these at runtime; bundling them breaks the plugin.
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2022',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  plugins: [
    sveltePlugin({
      preprocess: sveltePreprocess(),
      compilerOptions: {
        dev: !prod,
        // Inline any component CSS into the bundle. Obsidian only loads a single
        // styles.css, so a separate CSS output file would silently be dropped.
        css: 'injected',
      },
    }),
  ],
};

if (prod) {
  await esbuild.build(config);
} else {
  const ctx = await esbuild.context(config);
  await ctx.watch();
}
